apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-auth
  namespace: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-auth
  template:
    metadata:
      labels:
        app: nestjs-auth
    spec:
      containers:
        - name: nestjs-auth
          image: joseerisvaldo/nestjs-auth:latest
          ports:
            - containerPort: 3333
